import { useState } from 'react';
import { useSim } from '../game/hooks';
import { DecisionCard } from '../shell/DecisionCard';
import { Empty, Tabs } from '../components/ui';

export function Decisions() {
  const s = useSim();
  const [tab, setTab] = useState<'open' | 'history'>('open');
  const open = s.decisions.filter((d) => !d.resolved).sort((a, b) => a.expiresDay - b.expiresDay);
  const done = s.decisions.filter((d) => d.resolved);
  return (
    <div>
      <div className="page-head"><div><h1>Decisions</h1><p>Choices, opportunities and crises generated by the simulation. Unanswered decisions resolve to their default when they expire.</p></div></div>
      <Tabs value={tab} onChange={setTab} tabs={[{ id: 'open', label: `Open (${open.length})` }, { id: 'history', label: `History (${done.length})` }]} />
      <div className="stack">
        {(tab === 'open' ? open : done).map((d) => <DecisionCard key={d.id} d={d} />)}
        {tab === 'open' && !open.length && <Empty>No open decisions. Opportunities appear as the market evolves — advance time.</Empty>}
        {tab === 'history' && !done.length && <Empty>No decisions made yet.</Empty>}
      </div>
    </div>
  );
}
